More efficient packaging when NO_LIBC is specified. (#8)
* Package only the app deps when NO_LIBC is defined

* Remove algorithm header

* Set the AWS_EXECUTION_ENV env. variable

* Add tests for the  NO_LIBC variant of packaging in the CI

* Append to LD_LIBRARY_PATH rather than prepend

diff --git a/packaging/packager b/packaging/packager
--- a/packaging/packager
+++ b/packaging/packager
@@ -77,10 +77,16 @@ function package_libc_via_rpm() {
 
 PKG_BIN_FILENAME=`basename "$PKG_BIN_PATH"`
 PKG_DIR=tmp
+PKG_LD=""
 
-list=`ldd "$PKG_BIN_PATH" | awk '{print $(NF-1)}'`
+list=$(ldd "$PKG_BIN_PATH" | awk '{print $(NF-1)}')
+libc_libs=()
+libc_libs+=$(package_libc_via_dpkg)
+libc_libs+=$(package_libc_via_rpm)
+libc_libs+=$(package_libc_via_pacman)
+
 if [[ $INCLUDE_LIBC == true ]]; then
-    list="$list $(package_libc_via_dpkg) $(package_libc_via_rpm) $(package_libc_via_pacman)"
+    list+=$libc_libs;
 fi
 
 mkdir -p "$PKG_DIR/bin" "$PKG_DIR/lib"
@@ -90,6 +96,13 @@ do
     if [[ ! -f $i ]]; then # ignore linux-vdso.so.1
         continue
     fi
+
+    if [[ $INCLUDE_LIBC == false ]]; then
+        matched=$(echo $libc_libs | grep --count $i) || true # prevent the non-zero exit status from terminating the script
+        if [ $matched -gt 0 ]; then
+            continue
+        fi
+    fi
     cp $i $PKG_DIR/lib
     filename=`basename $i`
     if [[ -z "${filename##ld-*}" ]]; then
@@ -97,25 +110,28 @@ do
     fi
 done
 
-bootstrap_script="#!/bin/bash\n
-\n
-set -euo pipefail\n
-\n
-exec \$LAMBDA_TASK_ROOT/lib/$PKG_LD --library-path \$LAMBDA_TASK_ROOT/lib \$LAMBDA_TASK_ROOT/bin/$PKG_BIN_FILENAME \${_HANDLER}\n
-"
+bootstrap_script=$(cat <<EOF
+#!/bin/bash
+set -euo pipefail
+export AWS_EXECUTION_ENV=lambda-cpp
+exec \$LAMBDA_TASK_ROOT/lib/$PKG_LD --library-path \$LAMBDA_TASK_ROOT/lib \$LAMBDA_TASK_ROOT/bin/$PKG_BIN_FILENAME \${_HANDLER}
+EOF
+)
 
-bootstrap_script_no_libc="#!/bin/bash\n
-\n
-set -euo pipefail\n
-\n
-exec \$LAMBDA_TASK_ROOT/lib/$PKG_LD --library-path \$LD_LIBRARY_PATH:\$LAMBDA_TASK_ROOT/lib \$LAMBDA_TASK_ROOT/bin/$PKG_BIN_FILENAME \${_HANDLER}\n
-"
+bootstrap_script_no_libc=$(cat <<EOF
+#!/bin/bash
+set -euo pipefail
+export AWS_EXECUTION_ENV=lambda-cpp
+export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:\$LAMBDA_TASK_ROOT/lib
+exec \$LAMBDA_TASK_ROOT/bin/$PKG_BIN_FILENAME \${_HANDLER}
+EOF
+)
 
 cp "$PKG_BIN_PATH" "$PKG_DIR/bin"
 if [[ $INCLUDE_LIBC == true ]]; then
-    echo -e $bootstrap_script > "$PKG_DIR/bootstrap"
+    echo -e "$bootstrap_script" > "$PKG_DIR/bootstrap"
 else
-    echo -e $bootstrap_script_no_libc > "$PKG_DIR/bootstrap"
+    echo -e "$bootstrap_script_no_libc" > "$PKG_DIR/bootstrap"
 fi
 chmod +x "$PKG_DIR/bootstrap"
 # some shenanigans to create the right layout in the zip file without extraneous directories
